### ISSUE TITLE
custom data URL no longer working from script.js after recent June code updates

### ISSUE THREAD

**Issue by wakruse** [connormanning/potree.entwine.io#6]
I can no longer specify a custom entwine data source URL using "http://potree.entwine.io/data/custom.html". "script.js" (line 349) inserts http://na-c.entwine.io/ instead of the base URL I provide. The name of my custom data source appended to this URL is correct. I get the follow error:

potree.js:4902 GET http://na-c.entwine.io/2017_Almanor_rgb_entwine/entwine.json 403 (Forbidden) potree.js:4902

This worked correctly before the recent code updates. The demo data sources provided that I tested are working.

**Comment by connormanning** [comment]
Your custom URL must be prefixed with `http://` or `https://`.  For example: [http://potree.entwine.io/data/custom.html?r="http://na.entwine.io/autzen/entwine.json"](http://potree.entwine.io/data/custom.html?r=%22http://na.entwine.io/autzen/entwine.json%22)

**Comment by wakruse** [comment]
Here is the full URL I've been using which had been working correctly:
http://potree.entwine.io/data/custom.html?s=https://anycompany.com/veg1&r=2017_Almanor_rgb_entwine

My understanding is that potree should then generate the following:
https://anycompany.com/veg1/2017_Almanor_rgb_entwine/entwine.json
rather than what is does generate: 
http://na-c.entwine.io/2017_Almanor_rgb_entwine/entwine.json

Thanks

**Comment by connormanning** [comment]
The `s` parameter should not be used with this website - that is dead code that should be removed. 
 It represented a Greyhound server which is no longer used.  The potree.entwine.io website (and thus this repository) is used to demo EPT datasets, which require a full URL in the `r` (for "resource") query parameter.

**Comment by wakruse** [comment]
I now get the correct URL but realize that the entwine.json file does not exist. This data set was indexed with entwine build in early June. I'm assuming that I overlooked the subsequent updates to the entwine code that took place since then and will need to rebuild the index. Is this correct? Thanks

**Comment by connormanning** [comment]
Yes, see connormanning/entwine/pull/98.  This is simply the repo for the http://potree.entwine.io website, so its purpose is just to demo our latest resources.  The custom.html link is provided as a convenience for easy access to Entwine output viewing for README getting-started documentation - so this repository shouldn't be relied on for long-term URLs since it is potentially subject to change.

You could modify it using an older version as a template if you would like to host your own Greyhound-service viewer.  You may also find the examples at potree.org useful to build from, which also include a Greyhound example (which is currently non-working since we've shut down our servers in favor of statically served EPT).

**Comment by wakruse** [comment]
I really appreciate your quick response with this additional information. I began evaluating entwine in recent months and I have more to learn. I'm looking at the entwine/greyhound/pdal tool set to help support custom processing, multi-user data access and ad-hoc viewing of a growing state scale LiDAR data archive for a client. The results are very encouraging at this time.
